config/routes.rb
WaterDistrict::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  
  namespace :admin do
  	match 'login' => "session#new", :via => :get,	:as => "login_page"
  	match 'login' => "session#create", :via => :post,	:as => "login_user"
  	match 'logout' => "session#destroy", :via => :get,	:as => "logout_user"
  	match '/' => 'main#index', :via => :get

		match '/index' => 'main#index', :via => :get
		resources :pages
    resources :users
    resources :banners
    resources :contacts
    match 'commons/update' => 'main#common_update', :via => :put, :as => 'common_update'
  end
  match '/' => 'home#index', via: :get
  match '/home' => 'home#index', :via => :get
  match '/contact-us' => 'pages#contacts', via: :get
  match '/(:page_url)' => 'pages#show', via: :get, constraints: { :page_url => /.*/ }, as: 'pages'
  root :to => 'home#index'

  

end

app/views/admin/pages/edit.html.erb
<% content_for :page_style do %>
    <!-- Start specific page styles -->

    <!-- End specific page styles -->
<% end %>
<% content_for :page_content do %>
    <div class='row'>
      <div class='col-lg-12'>

        <%= generate_breadcrumbs %>
        <div class='panel panel-primary'>
          <div class='panel-heading'>

            <%= action_name.capitalize %> <%= controller_name.capitalize.singularize %>
          </div>
          <div class='panel-body'>
            <% if @page.errors.any? %>
                <div class='alert alert-danger'>
                  <ul>
                    <% @page.errors.full_messages.each do |err| %>
                        <li><%= err %></li>
                    <% end %>
                  </ul>

                </div>
            <% end %>
            <%= form_for(@page, :as => :page, :validate => true, :html => { :multipart => true }, :url => admin_page_path(@page)) do |f| %>
                <br/>
                <div class='form-group clearfix'>
                  <%= f.label :page_title, 'Page Title', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>

                    <%= f.text_field :page_title, :class => 'form-control input-md  required', :placeholder => 'Page Title', :required => true %>

                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :page_subtitle, 'Page Subtitle', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :page_subtitle, :class => 'form-control input-md', :placeholder => 'Page Subtitle' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :browser_title, 'Browser Title', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :browser_title, :class => 'form-control input-md', :placeholder => 'Browser Title' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%
                     url = @page.page_url.split('/')
                     if url.length == 1
                       page_url = @page.page_url
                     else
                       url.shift
                       page_url = url.join('/')
                     end

                  %>
                  <%= f.label :page_url, 'Page Url', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :page_url, :class => 'form-control input-md', :placeholder => 'Page Url', :value => page_url %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :body, :class => 'col-md-2 control-label' %>
                  <div class='col-md-10'>
                    <%= f.text_area :body, :class => 'ckeditor' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :short_body, 'Short Body', :class => 'col-md-2 control-label' %>
                  <div class='col-md-10'>
                    <%= f.text_area :short_body, :class => 'form-control input-md', :rows => 7, :cols => 40, :placeholder => 'Short Body' %>
                  </div>
                </div>
		            <div class="form-group clearfix ">
		              <%= f.label :meta_title, "Meta Title", :class => "col-md-2 control-label" %>
		              <div class="col-md-8">
		                 <%= f.text_field :meta_title, :class => "form-control input-md  required", :placeholder => "Meta Title" %>

		              </div>
		            </div>
		            <div class="form-group clearfix">
		              <%= f.label :meta_description, "Meta Description", :class => "col-md-2 control-label" %>
		              <div class="col-md-10">
		                <%= f.text_area :meta_description, :class => "form-control input-md", :rows => 7, :cols => 40, :placeholder => "Meta Description" %>
		              </div>
		            </div>
                <div class='form-group clearfix'>
                  <%= f.label :page_styles, 'Page Styles', :class => 'col-md-2 control-label' %>
                  <div class='col-md-10'>
                    <%= f.text_area :page_styles, :class => 'form-control input-md', :rows => 7, :cols => 40, :placeholder => 'Page Styles' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :page_scripts, 'Page Scripts', :class => 'col-md-2 control-label' %>
                  <div class='col-md-10'>
                    <%= f.text_area :page_scripts, :class => 'form-control input-md', :rows => 7, :cols => 40, :placeholder => 'Page Scripts' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <% @pageSet = Page.where('activate = ? AND id <> ?', true, @page.id )%>
                  <%= f.label :page_id, 'Parent', :class => 'col-md-2 control-label' %>
                  <div class='col-md-5'>
                    <%= f.collection_select :page_id, @pageSet, :id, :page_title, {:include_blank => true}, {:class => 'form-control'} %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :publish_date, 'Publish Date', :class => 'col-md-2 control-label' %>
                  <div class='col-md-4'>
                    <div class='input-group date'>
                      <%= f.text_field :publish_date, :class => 'form-control datepicker', :placeholder => 'Publish Date' %>
                      <span class='input-group-addon'><span class='glyphicon glyphicon-calendar'></span></span>
                    </div>

                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :display_order, 'Display Order', :class => 'col-md-2 control-label num' %>
                  <div class='col-md-2'>
                    <%= f.text_field :display_order, :class => 'form-control input-md num', :placeholder => 'Display Order' %>
                  </div>
                </div>
		            <div class="form-group clearfix">

		              <div class="col-md-8 col-md-offset-2">
		                <%= f.check_box :is_full_page %> Is Full Page?
		              </div>
		            </div>
                <div class='form-group clearfix'>

                  <div class='col-md-8 col-md-offset-2'>
                    <%= f.check_box :is_skip %> Skip?
                  </div>
                </div>
                <div class='form-group clearfix'>

                  <div class='col-md-8 col-md-offset-2'>
                    <%= f.check_box :activate %> Is Published?
                  </div>
                </div>
                <div class='form-group clearfix'>

                  <div class='col-md-8 col-md-offset-2'>
                    <%= f.check_box :show_in_menu %> Show in menu?
                  </div>
                </div>
                <div class='row col-md-12'>
                  <div class='pull-right'>
                    <a href="<%= url_for(:controller => controller_name, :action => 'index') %>" class='btn btn-default btn-sm'>Cancel</a>
                    <%= f.submit 'Save', :class => 'btn btn-primary btn-sm' %>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/admin/pages/index.html.erb
<% content_for :page_content do %>

<div class="row">
    <div class="col-lg-12">


        <a href="<%= url_for(:controller => controller_name, :action => "new")%>" class="btn btn-sm btn-danger">Add New</a>

        <div class="clearfix"></div>
        <br/>

        <div class="panel panel-primary">
                <div class="panel-heading">
                    <%= controller_name.capitalize %> Listing
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">


                    <div class="table-responsive">
                        <% if !@pages.empty? %>
                            <table id="table-listing" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th class="text-center">Last Updated By</th>
                                        <th class="text-center">Is Published?</th>
                                        <th class="text-center">Last Modified At</th>
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @pages.each do |p| %>
                                    	<tr data-id="<%= p.id.to_s %>" data-resource="<%= controller_name %>">
	                                        <td><%= p.page_title %></td>
	                                        <td class="text-center"><%= (p.last_updated_by.blank? ? '-': p.user.username )%></td>
	                                        <td class="text-center" data-object="<%= {:scope => 'activate', :value => p.activate, :target => controller_name }.to_json %>">
	                                          <% if p.activate %>
												<a href="<%= admin_common_update_path(:id => p.id, :scope => 'activate', :target => controller_name) %>" class="btn btn-success btn-circle toggle-activation" data-method='put'><i class="fa fa-check"></i></a>
	                                          <% else %>
												<a href="<%= admin_common_update_path(:id => p.id, :scope => 'activate', :target => controller_name)%>" class="btn btn-danger btn-circle toggle-activation" data-method='put'><i class="fa fa-times"></i></a>
	                                          <% end %>
	                                          </a>
	                                        </td>
	                                        <td class="text-center">
	                                          <%= time_ago_in_words(p.updated_at) %>
	                                        </td>
	                                        <td class="text-center">
	                                            
	                                              <a href="<%= url_for(:controller => controller_name, :action => "edit", :id => p) %>" class="btn btn-warning btn-sm" title="Edit"><i class="fa fa-edit"></i></a>
	                                              <a href="<%= url_for(:controller => controller_name, :action => "destroy", :id => p) %>" class="btn btn-danger btn-sm" <% if p.is_root? || p.is_contact? %>disabled='disabled'<% end %> data-confirm="Are you sure you want to continue this action?" data-method="delete" title="Delete"><i class="fa fa-trash-o"></i></a>
	                                            
	                                        </td>
	                                    </tr>
                                    <% end %>
                                </tbody>
                            </table>
                        <% else %>
                            <p class="lead">No Pages Yet!</p>
                        <% end %>

                            </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>

    <!-- /.col-lg-12 -->
</div>
<% end %>

app/views/admin/pages/new.html.erb
<% content_for :page_style do %>
<!-- Start specific page styles -->

<!-- End specific page styles -->
<% end %>
<% content_for :page_content do %>
<div class="row">
  <div class="col-lg-12">

    <%= generate_breadcrumbs %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <%= action_name.capitalize %> <%= controller_name.capitalize.singularize %>
      </div>
      <div class="panel-body">
        <% if @page.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @page.errors.full_messages.each do |err| %>
            <li><%= err %></li>
            <% end %>
          </ul>

        </div>
        <% end %>
        <%= form_for(@page, :as => :page, :validate => true, :html => { :multipart => true }, :url => admin_pages_path) do |f| %>
            <br/>
            <div class="form-group clearfix ">
              <%= f.label :page_title, "Page Title", :class => "col-md-2 control-label" %>
              <div class="col-md-8">
                 <%= f.text_field :page_title, :class => "form-control input-md  required", :placeholder => "Page Title", :required => true %>

              </div>
            </div>
            <div class="form-group clearfix">
              <%= f.label :page_subtitle, "Page Subtitle", :class => "col-md-2 control-label" %>
              <div class="col-md-8">
                <%= f.text_field :page_subtitle, :class => "form-control input-md", :placeholder => "Page Subtitle" %>
              </div>
            </div>
            <div class="form-group clearfix">
              <%= f.label :browser_title, "Browser Title", :class => "col-md-2 control-label" %>
              <div class="col-md-8">
                <%= f.text_field :browser_title, :class => "form-control input-md", :placeholder => "Browser Title" %>
              </div>
            </div>
            <div class="form-group clearfix">
              <%= f.label :page_url, "Page Url", :class => "col-md-2 control-label" %>
              <div class="col-md-8">
                <%= f.text_field :page_url, :class => "form-control input-md", :placeholder => "Page Url" %>
              </div>
            </div>
            <div class="form-group clearfix">
              <%= f.label :body, :class => "col-md-2 control-label" %>
              <div class="col-md-10">
                <%= f.text_area :body, :class => "ckeditor" %>
              </div>
            </div>
            <div class="form-group clearfix">
              <%= f.label :short_body, "Short Body", :class => "col-md-2 control-label" %>
              <div class="col-md-10">
                <%= f.text_area :short_body, :class => "form-control input-md", :rows => 7, :cols => 40, :placeholder => "Short Body" %>
              </div>
            </div>
            <div class="form-group clearfix ">
              <%= f.label :meta_title, "Meta Title", :class => "col-md-2 control-label" %>
              <div class="col-md-8">
                 <%= f.text_field :meta_title, :class => "form-control input-md  required", :placeholder => "Meta Title" %>

              </div>
            </div>
            <div class="form-group clearfix">
              <%= f.label :meta_description, "Meta Description", :class => "col-md-2 control-label" %>
              <div class="col-md-10">
                <%= f.text_area :meta_description, :class => "form-control input-md", :rows => 7, :cols => 40, :placeholder => "Meta Description" %>
              </div>
            </div>
            <div class="form-group clearfix">
              <%= f.label :page_styles, "Page Styles", :class => "col-md-2 control-label" %>
              <div class="col-md-10">
                <%= f.text_area :page_styles, :class => "form-control input-md", :rows => 7, :cols => 40, :placeholder => "Page Styles" %>
              </div>
            </div>
            <div class="form-group clearfix">
              <%= f.label :page_scripts, "Page Scripts", :class => "col-md-2 control-label" %>
              <div class="col-md-10">
                <%= f.text_area :page_scripts, :class => "form-control input-md", :rows => 7, :cols => 40, :placeholder => "Page Scripts" %>
              </div>
            </div>
            <div class="form-group clearfix">
              <% @pageSet = Page.where("activate = ?", true )%>
              <%= f.label :page_id, "Parent", :class => "col-md-2 control-label" %>
              <div class="col-md-5">
                <%= f.collection_select :page_id, @pageSet, :id, :page_title, {:include_blank => true}, {:class => 'form-control'} %>
              </div>
            </div>
            <div class="form-group clearfix">
              <%= f.label :publish_date, "Publish Date", :class => "col-md-2 control-label" %>
              <div class="col-md-4">
                <div class='input-group date'>
                  <%= f.text_field :publish_date, :class => "form-control datepicker", :placeholder => "Publish Date" %>
                  <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                </div>

              </div>
            </div>
            <div class="form-group clearfix">
              <%= f.label :display_order, "Display Order", :class => "col-md-2 control-label num" %>
              <div class="col-md-2">
                <%= f.text_field :display_order, :class => "form-control input-md num", :placeholder => "Display Order" %>
              </div>
            </div>
            <div class="form-group clearfix">

              <div class="col-md-8 col-md-offset-2">
                <%= f.check_box :is_full_page %> Is Full Page?
              </div>
            </div>
            <div class="form-group clearfix">

              <div class="col-md-8 col-md-offset-2">
                <%= f.check_box :is_skip %> Skip?
              </div>
            </div>
            <div class="form-group clearfix">

              <div class="col-md-8 col-md-offset-2">
                <%= f.check_box :activate %> Is Published?
              </div>
            </div>
            <div class="form-group clearfix">

              <div class="col-md-8 col-md-offset-2">
                <%= f.check_box :show_in_menu %> Show in menu?
              </div>
            </div>
            <div class="row col-md-12">
              <div class="pull-right">
                <a href="<%= url_for(:controller => controller_name, :action => 'index') %>" class="btn btn-default btn-sm">Cancel</a>
                <%= f.submit "Save", :class => "btn btn-primary btn-sm" %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>