config/routes.rb
WaterDistrict::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  
  namespace :admin do
  	match 'login' => "session#new", :via => :get,	:as => "login_page"
  	match 'login' => "session#create", :via => :post,	:as => "login_user"
  	match 'logout' => "session#destroy", :via => :get,	:as => "logout_user"
  	match '/' => 'main#index', :via => :get

		match '/index' => 'main#index', :via => :get
		resources :pages
    resources :users
    resources :banners
    resources :contacts
    match 'commons/update' => 'main#common_update', :via => :put, :as => 'common_update'
  end
  match '/' => 'home#index', via: :get
  match '/home' => 'home#index', :via => :get
  match '/contact-us' => 'pages#contacts', via: :get
  match '/(:page_url)' => 'pages#show', via: :get, constraints: { :page_url => /.*/ }, as: 'pages'
  root :to => 'home#index'

  

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  require 'iconv'
  belongs_to :user, :class_name => 'User', :foreign_key => :last_updated_by
  has_many :page_banners, :dependent => :destroy
  has_many :pages, :through => :page_banners
  has_attached_file :banner, :styles => {
      :large => "1280x400>",
      :medium => "960x300>",
      :thumb => "120x50>"
  },
  # :url  => '/images/banners/:id/:style/:basename.:extension',
  # :path => ':rails_root/public/images/banners/:id/:style/:basename.:extension',
  # :default_url => '/assets/frontend/no-image.jpg',
  :storage => :s3,
  :s3_credentials => S3_CREDENTIALS,
  :url  => "/banners/:id/:style/:basename.:extension",
  :path => "/banners/:id/:style/:basename.:extension",
  :default_url => "/assets/no-image-available.png",
  :default_style => :medium
  validates_attachment_content_type :banner, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :banner
  before_post_process :transliterate_file_name

  def transliterate_file_name
    extension = File.extname(banner.original_filename).gsub(/^\.+/, '')
    filename = banner.original_filename.gsub(/\.#{extension}$/, '')
    self.banner.instance_write(:file_name, "#{transliterate(filename)}.#{transliterate(extension)}")
  end

  def transliterate(str)
    s = Iconv.iconv('ascii//ignore//translit', 'utf-8', str).to_s
    s.downcase!
    s.gsub!(/'/, '')
    s.gsub!(/[^A-Za-z0-9]+/, ' ')
    s.strip!
    s.gsub!(/\ +/, '-')
    return s
  end
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < ApplicationController
  include Admin::MainModule
  before_filter :set_title
  before_filter :check_role, :only => [:destroy]

  def check_role
    if is_editor?
      @banners = Banner.all
      flash[:warning] = 'Only admin role is allowed to this action!'
      redirect_to(:action => 'index')
    end
  end

  def set_title
    @title = 'Banners Management'
  end

  def index
    @banners = Banner.all
  end

  def show
    @banner = Topbanner.all
    render :action => "index"
  end

  def new
    @banner = Banner.new
  end

  def edit
    @banner = Banner.find(params[:id])
  end

  def create
    @banner = Banner.new(banner_params)
    @banner.last_updated_by = current_user.id
    if @banner.save
      flash[:success] = 'Banner created successfully!'
      redirect_to(:url => admin_banners_path, :notice => 'Create Banner Successfully!')
    else
      render :action => "new"
    end
  end

  def update
    @banner = Banner.find(params[:id])
    @banner.last_updated_by = current_user.id
    if @banner.update_attributes(banner_params)
      flash[:success] = 'Banner updated successfully!'
      redirect_to admin_banners_path
    else
      render :action => "edit"
    end
  end

  def destroy
    @banner = Banner.find(params[:id])
    @banner.destroy

    redirect_to(admin_banners_path)
  end


  private

  def banner_params
    params.require(:banner).permit!
  end
end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

app/views/admin/banners/edit.html.erb
<% content_for :page_style do %>
    <!-- Start specific page styles -->

    <!-- End specific page styles -->
<% end %>
<% content_for :page_content do %>
    <div class="row">
      <div class="col-lg-12">

        <%= generate_breadcrumbs %>
        <div class="panel panel-primary">
          <div class="panel-heading">
            <%= action_name.capitalize %> <%= controller_name.capitalize.singularize %>
          </div>
          <div class="panel-body">
            <% if @banner.errors.any? %>
                <div class="alert alert-danger">
                  <ul>
                    <% @banner.errors.full_messages.each do |err| %>
                        <li><%= err %></li>
                    <% end %>
                  </ul>

                </div>
            <% end %>
            <%= form_for(@banner, :as => :banner, :validate => true, :html => { :multipart => true }, :url => admin_banner_path(@banner)) do |f| %>
                <br/>
                <fieldset>
                  <div class="form-group clearfix ">
                    <%= f.label :title, "Title", :class => "col-md-2 control-label" %>
                    <div class="col-md-8">
                      <%= f.text_field :title, :class => "form-control input-md", :placeholder => "Title" %>

                    </div>
                  </div>
                  <div class="form-group clearfix">
                    <%= f.label :caption, "Caption", :class => "col-md-2 control-label" %>
                    <div class="col-md-8">
                      <%= f.text_field :caption, :class => "form-control input-md", :placeholder => "Caption" %>
                    </div>
                  </div>
                  <div class="form-group clearfix">
                    <%= f.label :url, "Link To", :class => "col-md-2 control-label" %>
                    <div class="col-md-8">
                      <%= f.text_field :url, :class => "form-control input-md", :placeholder => "Link to" %>
                    </div>
                  </div>
                  <div class="form-group clearfix">

                    <div class="col-md-8 col-md-offset-2">
                      <%= f.check_box :featured %> Is Featured? <small class="text-info">(If ticked will be displayed on the main page)</small>
                    </div>
                  </div>
                  <div class="form-group clearfix">

                    <div class="col-md-8 col-md-offset-2">
                      <%= f.check_box :activate %> Is Enabled?
                    </div>
                  </div>
                  <div class="form-group clearfix">
                    <%= f.label :banner, "Upload Banner", :class => "col-md-2 control-label" %>
	                  <div class="col-md-8">
	                  	<div class="fileinput fileinput-new" data-provides="fileinput">
						  <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 120px;">
						  	<%= image_tag(@banner.banner.url(:thumb))%>
						  </div>
						  <div>
						    <span class="btn btn-default btn-file">
						    	<span class="fileinput-new">Select image</span>
						    	<span class="fileinput-exists">Change</span>
						    	<%= f.file_field :banner %>
					    	</span>
					    	<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
						  </div>
						</div>
	                    
	                  </div>
	                
	              </div>
	            <div class="form-group clearfix">
	              <% @pageSet = Page.where("activate = ?", true )%>
	              <%= label :page_ids, "Apply to which pages?", :class => "col-md-2 control-label" %>
	              <div class="col-md-4">
	              	<%= collection_select(:banner, :page_ids, Page.all,
                  :id, :page_title, {:selected => @banner.page_ids, :include_blank => true}, {:multiple => true, :class => 'selectpicker'}) %>
	              </div>
	            </div>
	            
                </fieldset>
                <div class="row col-md-12">
                  <div class="pull-right">
                    <a href="<%= url_for(:controller => controller_name, :action => 'index') %>" class="btn btn-default btn-sm">Cancel</a>
                    <%= f.submit "Save", :class => "btn btn-primary btn-sm" %>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/admin/banners/index.html.erb
<% content_for :page_content do %>

    <div class="row">
      <div class="col-lg-12">


        <a href="<%= url_for(:controller => controller_name, :action => "new")%>" class="btn btn-sm btn-danger">Add New</a>

        <div class="clearfix"></div>
        <br/>

        <div class="panel panel-primary">
          <div class="panel-heading">
            <%= controller_name.capitalize %> Listing
          </div>
          <!-- /.panel-heading -->
          <div class="panel-body">


            <div class="table-responsive">
              <% if !@banners.empty? %>
                  <table id="table-listing" class="table table-striped table-bordered">
                    <thead>
                    <tr>
                      <th>Banner</th>
                      <th class="text-center">Is Enabled?</th>
                      <th class="text-center">Last Updated By</th>
                      <th class="text-center">Last Modified At</th>
                      <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @banners.each do |b| %>
                        <tr data-id="<%= b.id.to_s %>" data-resource="<%= controller_name %>">
                          <td><a href="<%= b.banner.url(:large) %>" target="_blank"><%= image_tag(b.banner.url(:thumb)) %></a></td>
                          <td class="text-center">
                            <% if b.activate %>
                                <button type="button" class="btn btn-success btn-circle toggle-activation"><i class="fa fa-check"></i></button>
                            <% else %>
                                <button type="button" class="btn btn-danger btn-circle toggle-activation"><i class="fa fa-times"></i></button>
                            <% end %>
                          </td>
                          <td class="text-center"><%= (b.last_updated_by.blank? ? '-': b.user.username )%></td>
                          <td class="text-center">
                            <%= time_ago_in_words(b.updated_at) %>
                          </td>
                          <td class="text-center">
                            <a>
                              <a href="<%= url_for(:controller => controller_name, :action => "edit", :id => b) %>" class="btn btn-warning btn-sm" title="Edit"><i class="fa fa-edit"></i></a>
                              <a href="<%= url_for(:controller => controller_name, :action => "destroy", :id => b) %>" class="btn btn-danger btn-sm" data-confirm="Are you sure you want to continue this action?" data-method="delete" title="Delete"><i class="fa fa-trash-o"></i></a>
                            </a>
                          </td>
                        </tr>
                    <% end %>
                    </tbody>
                  </table>
              <% else %>
                  <p class="lead">No Banners Yet!</p>
              <% end %>

            </div>
            <!-- /.table-responsive -->
          </div>
          <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
      </div>

      <!-- /.col-lg-12 -->
    </div>
<% end %>

app/views/admin/banners/new.html.erb
<% content_for :page_style do %>
    <!-- Start specific page styles -->

    <!-- End specific page styles -->
<% end %>
<% content_for :page_content do %>
    <div class="row">
      <div class="col-lg-12">

        <%= generate_breadcrumbs %>
        <div class="panel panel-primary">
          <div class="panel-heading">
            <%= action_name.capitalize %> <%= controller_name.capitalize.singularize %>
          </div>
          <div class="panel-body">
            <% if @banner.errors.any? %>
                <div class="alert alert-danger">
                  <ul>
                    <% @banner.errors.full_messages.each do |err| %>
                        <li><%= err %></li>
                    <% end %>
                  </ul>

                </div>
            <% end %>
                <%= form_for(@banner, :as => :banner, :validate => true, :html => { :multipart => true }, :url => admin_banners_path) do |f| %>
                <br/>
                <fieldset>
                <div class="form-group clearfix ">
                  <%= f.label :title, "Title", :class => "col-md-2 control-label" %>
                  <div class="col-md-8">
                    <%= f.text_field :title, :class => "form-control input-md", :placeholder => "Title" %>

                  </div>
                </div>
                <div class="form-group clearfix">
                  <%= f.label :caption, "Caption", :class => "col-md-2 control-label" %>
                  <div class="col-md-8">
                    <%= f.text_field :caption, :class => "form-control input-md", :placeholder => "Caption" %>
                  </div>
                </div>
                <div class="form-group clearfix">
                  <%= f.label :url, "Link To", :class => "col-md-2 control-label" %>
                  <div class="col-md-8">
                    <%= f.text_field :url, :class => "form-control input-md", :placeholder => "Link to" %>
                  </div>
                </div>
                <div class="form-group clearfix">

                  <div class="col-md-8 col-md-offset-2">
                    <%= f.check_box :featured %> Is Featured? <small>(If ticked will be displayed on the main page)</small>
                  </div>
                </div>
                <div class="form-group clearfix">

                  <div class="col-md-8 col-md-offset-2">
                    <%= f.check_box :activate %> Is Enabled?
                  </div>
                </div>

                <div class="form-group clearfix">
                  <%= f.label :banner, "Upload Banner", :class => "col-md-2 control-label" %>
                  <div class="col-md-8">
                  	<div class="fileinput fileinput-new" data-provides="fileinput">
					  <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 120px;height:50px;"></div>
					  <div>
					    <span class="btn btn-default btn-file">
					    	<span class="fileinput-new">Select image</span>
					    	<span class="fileinput-exists">Change</span>
					    	<%= f.file_field :banner %>
				    	</span>
				    	<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
					  </div>
					</div>
                    
                  </div>
                </div>
	            <div class="form-group clearfix">
	              <% @pageSet = Page.where("activate = ?", true )%>
	              <%= label :page_ids, "Apply to which pages?", :class => "col-md-2 control-label" %>
	              <div class="col-md-4">
	              	<%= collection_select(:banner, :page_ids, Page.all,
                  :id, :page_title, {:selected => @banner.page_ids, :include_blank => true}, {:multiple => true, :class => 'selectpicker'}) %>
	              </div>
	            </div>
                </fieldset>
                <div class="row col-md-12">
                  <div class="pull-right">
                    <a href="<%= url_for(:controller => controller_name, :action => 'index') %>" class="btn btn-default btn-sm">Cancel</a>
                    <%= f.submit "Save", :class => "btn btn-primary btn-sm" %>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>