config/routes.rb
WaterDistrict::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  
  namespace :admin do
  	match 'login' => "session#new", :via => :get,	:as => "login_page"
  	match 'login' => "session#create", :via => :post,	:as => "login_user"
  	match 'logout' => "session#destroy", :via => :get,	:as => "logout_user"
  	match '/' => 'main#index', :via => :get

		match '/index' => 'main#index', :via => :get
		resources :pages
    resources :users
    resources :banners
    resources :contacts
    match 'commons/update' => 'main#common_update', :via => :put, :as => 'common_update'
  end
  match '/' => 'home#index', via: :get
  match '/home' => 'home#index', :via => :get
  match '/contact-us' => 'pages#contacts', via: :get
  match '/(:page_url)' => 'pages#show', via: :get, constraints: { :page_url => /.*/ }, as: 'pages'
  root :to => 'home#index'

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :company_name, :street, :country, :phone1, :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_length_of :phone1, :minimum => 7
  validates_length_of :fax, :minimum => 7, :allow_blank => true

  geocoded_by :address
  after_validation :geocode

  has_attached_file :logo, :styles => {
      :thumb => '40x40>'
  },
  :storage => :s3,
  :s3_credentials => S3_CREDENTIALS,
  :url  => '/company-logo/:id/:style/:basename.:extension',
  :path => '/company-logo/:id/:style/:basename.:extension',
  :default_url => '/assets/no-image-available.png',
  :default_style => :thumb
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
  before_post_process :transliterate_file_name

  def transliterate_file_name
    extension = File.extname(logo.original_filename).gsub(/^\.+/, '')
    filename = logo.original_filename.gsub(/\.#{extension}$/, '')
    self.logo.instance_write(:file_name, "#{transliterate(filename)}.#{transliterate(extension)}")
  end

  def transliterate(str)
    s = Iconv.iconv('ascii//ignore//translit', 'utf-8', str).to_s
    s.downcase!
    s.gsub!(/'/, '')
    s.gsub!(/[^A-Za-z0-9]+/, ' ')
    s.strip!
    s.gsub!(/\ +/, '-')
    return s
  end

  def address
    [street, city, province, country].compact.join(', ')
  end

end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController

  include Admin::MainModule
  before_filter :set_title

  def set_title
    @title = 'Contact Us Settings'
  end

  def index
    @contact = Contact.first
    render :show
  end

  def show
    @contact = Contact.first
  end

  def new

  end

  def create

  end

  def edit
    @contact = Contact.first
  end

  def update
    @contact = Contact.first
    @contact.last_updated_by = current_user.id
    if @contact.update_attributes(contact_params)
      flash[:success] =  "#{ controller_name.singularize.capitalize } successfully updated!"
      redirect_to admin_contacts_path
    else
      render :action => 'edit'
    end
  end

  def destroy

  end

  private

  def contact_params
    params.require(:contact).permit!
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/views/admin/contacts/edit.html.erb
<% content_for :page_style do %>
    <!-- Start specific page styles -->

    <!-- End specific page styles -->
<% end %>
<% content_for :page_content do %>
    <div class='row'>
      <div class='col-lg-12'>

        <%= generate_breadcrumbs %>
        <div class='panel panel-primary'>
          <div class='panel-heading'>

            <%= action_name.capitalize %> <%= controller_name.capitalize.singularize %>
          </div>
          <div class='panel-body'>
            <% if @contact.errors.any? %>
                <div class='alert alert-danger'>
                  <ul>
                    <% @contact.errors.full_messages.each do |err| %>
                        <li><%= err %></li>
                    <% end %>
                  </ul>

                </div>
            <% end %>
            <%= form_for(@contact, :as => :contact, :validate => true, :html => { :multipart => true }, :url => admin_contact_path(@contact)) do |f| %>
                <br/>
                <div class='form-group clearfix'>
                  <%= f.label :company_name, 'Company Name', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>

                    <%= f.text_field :company_name, :class => 'form-control input-md  required', :placeholder => 'Company Name', :required => true %>

                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :email, 'Email', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :email, :class => 'form-control input-md required', :placeholder => 'Email', :required => true %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :website, 'Website', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :website, :class => 'form-control input-md', :placeholder => 'Website' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :phone1, 'Phone 1', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :phone1, :class => 'form-control input-md required', :placeholder => 'Phone 1', :required => true %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :phone2, 'Phone 2', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :phone2, :class => 'form-control input-md', :placeholder => 'Phone 2' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :fax, 'Fax', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :fax, :class => 'form-control input-md', :placeholder => 'Fax' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :street, 'Street', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :street, :class => 'form-control input-md required', :placeholder => 'Street', :required => true %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :city, 'Town/City', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :city, :class => 'form-control input-md', :placeholder => 'City' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :province, 'Province', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :province, :class => 'form-control input-md', :placeholder => 'Province' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :country, 'Country', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.country_select :country, {:include_blank => true}, :class => 'selectpicker', :placeholder => 'Country', :required => true %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :business_hours_weekdays, 'Business Hours Weekdays', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :business_hours_weekdays, :class => 'form-control input-md', :placeholder => 'Business Hours Weekdays' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :business_hours_saturday, 'Business Hours Saturday', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :business_hours_saturday, :class => 'form-control input-md', :placeholder => 'Business Hours Saturday' %>
                  </div>
                </div>
                <div class='form-group clearfix'>
                  <%= f.label :business_hours_sunday, 'Business Hours Sunday', :class => 'col-md-2 control-label' %>
                  <div class='col-md-8'>
                    <%= f.text_field :business_hours_sunday, :class => 'form-control input-md', :placeholder => 'Business Hours Sunday' %>
                  </div>
                </div>
                <div class="form-group clearfix">
                  <%= f.label :logo, 'Upload Logo', :class => 'col-md-2 control-label' %>
                  <div class="col-md-8">
                    <div class="fileinput fileinput-new" data-provides="fileinput">
                      <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 120px;">
                        <%= image_tag(@contact.logo.url(:thumb))%>
                      </div>
                      <div>
						    <span class="btn btn-default btn-file">
						    	<span class="fileinput-new">Select image</span>
						    	<span class="fileinput-exists">Change</span>
                              <%= f.file_field :logo %>
					    	</span>
                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                      </div>
                    </div>

                  </div>
                </div>

                <div class='row col-md-12'>
                  <div class='pull-right'>
                    <a href="<%= url_for(:controller => controller_name, :action => 'index') %>" class='btn btn-default btn-sm'>Cancel</a>
                    <%= f.submit 'Save', :class => 'btn btn-primary btn-sm' %>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/admin/contacts/show.html.erb
<% content_for :page_style do %>
    <!-- Start specific page styles -->

    <!-- End specific page styles -->
<% end %>
<% content_for :page_content do %>
    <div class='row'>
      <div class='col-lg-12'>

        <%= generate_breadcrumbs %>
        <div class='panel panel-primary'>

          <div class='panel-heading'>

            <%= action_name.capitalize %> <%= controller_name.capitalize.singularize %>
          </div>
          <div class='panel-body'>
            <% if @contact.errors.any? %>
                <div class='alert alert-danger'>
                  <ul>
                    <% @contact.errors.full_messages.each do |err| %>
                        <li><%= err %></li>
                    <% end %>
                  </ul>

                </div>
            <% end %>

            <table class="table">
              <tbody>
                <tr>
                  <td class="strong">Company</td>
                  <td><%= @contact.company_name %></td>
                </tr>
                <tr>
                  <td class="strong">Email</td>
                  <td><%= @contact.email %></td>
                </tr>
                <tr>
                  <td class="strong">Website</td>
                  <td><%= @contact.website %></td>
                </tr>
                <tr>
                  <td class="strong">Phone 1</td>
                  <td><%= @contact.phone1 %></td>
                </tr>
                <tr>
                  <td class="strong">Phone 2</td>
                  <td><%= @contact.phone2 %></td>
                </tr>
                <tr>
                  <td class="strong">Fax</td>
                  <td><%= @contact.fax %></td>
                </tr>
                <tr>
                  <td class="strong">Street</td>
                  <td><%= @contact.street %></td>
                </tr>
                <tr>
                  <td class="strong">City</td>
                  <td><%= @contact.city %></td>
                </tr>
                <tr>
                  <td class="strong">Province</td>
                  <td><%= @contact.province %></td>
                </tr>
                <tr>
                  <td class="strong">Country</td>
                  <td><%= !@contact.country.nil? && !@contact.country.nil? ? country_name(@contact.country) : '' %></td>
                </tr>
                <tr>
                  <td class="strong">Business Hours Weekdays</td>
                  <td><%= @contact.business_hours_weekdays %></td>
                </tr>
                <tr>
                  <td class="strong">Business Hours Saturday</td>
                  <td><%= @contact.business_hours_saturday %></td>
                </tr>
                <tr>
                  <td class="strong">Business Hours Sunday</td>
                  <td><%= @contact.business_hours_sunday %></td>
                </tr>
                <tr>
                  <td class="strong">Logo</td>
                  <td><%= image_tag @contact.logo.url(:original), style:"width:50px;height:60px;border:1px solid #ccc;" %></td>
                </tr>
              </tbody>
            </table>


            <hr>
            <%= link_to 'Edit', edit_admin_contact_path(@contact), class: 'btn btn-sm btn-danger pull-right' %>
          </div>
        </div>
      </div>
    </div>
<% end %>