config/routes.rb
WaterDistrict::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  
  namespace :admin do
  	match 'login' => "session#new", :via => :get,	:as => "login_page"
  	match 'login' => "session#create", :via => :post,	:as => "login_user"
  	match 'logout' => "session#destroy", :via => :get,	:as => "logout_user"
  	match '/' => 'main#index', :via => :get

		match '/index' => 'main#index', :via => :get
		resources :pages
    resources :users
    resources :banners
    resources :contacts
    match 'commons/update' => 'main#common_update', :via => :put, :as => 'common_update'
  end
  match '/' => 'home#index', via: :get
  match '/home' => 'home#index', :via => :get
  match '/contact-us' => 'pages#contacts', via: :get
  match '/(:page_url)' => 'pages#show', via: :get, constraints: { :page_url => /.*/ }, as: 'pages'
  root :to => 'home#index'

  

end

app/views/layouts/_footer.html.erb
<div class="container"  style="background: #293541;color:#fff;width:100% !important;">



  <footer style="">
    <div class="container">
      <div class="row">
        <!-- Contact Us -->
        <div class="col-sm-4">
          <h3 class="text-color"><span class="border-color">Contact Us</span></h3>
          <div class="content">
            <p>
              Mariveles Water District<br>
              Provincial Road San Isidro<br>
              2105 Mariveles, Bataan, Philippines<br>
              Telephone: (047) 935-4635 <br>
              Hotline: (0921) 287-6851 <br>
            </p>
          </div>
        </div>
        <!-- Social icons -->
        <div class="col-sm-4">
          <h3 class="text-color"><span>Go Social</span></h3>
          <div class="content social">
            <p>Stay in touch with us:</p>
<!--             <ul class="list-inline">
              <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a></li>
              <li><a href="#" class="github"><i class="fa fa-github"></i></a></li>
              <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
              <li><a href="#" class="vk"><i class="fa fa-vk"></i></a></li>
              <li><a href="#" class="plus"><i class="fa fa-google-plus"></i></a></li>
            </ul> -->
          <%= render 'shared/fb_page_like' %>
          </div>
        </div>
        <!-- Subscribe -->
        <div class="col-sm-4">
          <h3 class="text-color"><span>Subscribe</span></h3>
          <div class="content">
            <p>Enter your e-mail below to subscribe to our free newsletter.<br>We promise not to bother you often!</p>
            <form class="form" role="form">
              <div class="row">
                <div class="col-sm-8">
                  <div class="input-group">
                    <label class="sr-only" for="subscribe-email">Email address</label>
                    <input type="email" class="form-control" id="subscribe-email" placeholder="Enter email">
					  <span class="input-group-btn">
					    <button type="submit" class="btn btn-default">OK</button>
					  </span>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <hr>
        </div>
      </div>
      <!-- Copyrights -->
      <div class="row">
        <div class="col-sm-12">
          <div class="col-md-6 col-xs-s6 col-sm-6">© Mariveles Water District <%= Time.now.year %>.</div>
          <div class="col-md-6 col-xs-s6 col-sm-6">Powered by: <a href="#" title="Inbox Business Solutions">Inbox Business Solutions</a></div>

        </div>
      </div>
    </div>

  </footer>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
      <a class="navbar-brand" href="/" style="">
        MARIWAD
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <%= raw(build_navs) %>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/_main_banners.html.erb
<% if @banners.any? %>
<div id="myCarousel" class="carousel slide">

  <!-- Indicators -->
  <% if @banners.size > 1 %>
  <ol class="carousel-indicators">
    <% @banners.each_with_index do |banner, index|%>
        <li data-target="#myCarousel" data-slide-to="<%= index.to_s %>" <% if banner == @banners.first %>class="active"<% end %>></li>
    <% end %>
  </ol>
  <% end %>
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <% @banners.each_with_index do |item, index|%>
        <div class="item <% if @banners.first == item %>active<% end %>">
          <div class="fill" style="">
            <img src="<%= item.banner.url(:large) %>"/>
          </div>
          <div class="carousel-caption" style="position:absolute;top:30px;">
            <div class="carousel-text">
              <% unless item.title.nil? %><h1 class="animated fadeInDownBig"><%= item.title %></h1><% end %>
              <% unless item.caption.nil? %>
                  <ul class="list-unstyled carousel-list">
                    <li class="animated bounceInLeft" style="padding:10px;"><span style=""><%= item.caption %></span></li>
                  </ul>
              <% end %>
            </div>
          </div>

        </div>
    <% end %>
  </div>

  <!-- Controls -->
  <% if @banners.size > 1 %>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
  <% end %>

</div>
<% end %>

app/views/layouts/_menu_sidebar.html.erb
<nav id="sidebar-menu" class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </li>
            <li id="li-main">
                <a href="<%= admin_path %>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li id="li-pages">
                <a href="<%= admin_pages_path %>"><i class="fa fa-book fa-fw"></i> Pages</a>
            </li>
            <li id="li-banners">
                <a href="<%= admin_banners_path %>"><i class="fa fa-flag-o"></i> Banners Management</a>
            </li>

            <li id="li-events">
                <a href="#"><i class="fa fa-calendar fa-fw"></i> Events</a>
            </li>
            <li id="li-users">
              <a href="<%= admin_users_path %>"><i class="fa fa-users fa-fw"></i> Users</a>
            </li>
            <li id="li-contacts">
                <a href="<%= admin_contact_path(Contact.first) %>"><i class="fa fa-suitcase fa-fw"></i> Company</a>
            </li>
        </ul>
        <!-- /#side-menu -->
    </div>
    <!-- /.sidebar-collapse -->
</nav>

app/views/layouts/administration.html.erb
<!DOCTYPE html>
<html lang="en"><head>
    
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Inbox Biz CMS</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <%= csrf_meta_tags %>
     <!-- Core CSS - Include with every page -->
  	<%= stylesheet_link_tag "css/bootstrap.min", media: "all" %>
  	<%= stylesheet_link_tag "font-awesome/css/font-awesome", media: "all" %>
  	
    <!-- Page-Level Plugin CSS - Dashboard -->
    <%= stylesheet_link_tag "css/plugins/morris/morris-0.4.3.min", media: "all" %>
    <%= stylesheet_link_tag "css/plugins/timeline/timeline", media: "all" %>
    <%= stylesheet_link_tag "css/plugins/dataTables/dataTables.bootstrap", media: "all" %>
    <%= stylesheet_link_tag "css/bootstrap-datepicker", media: "all" %>
    <%= stylesheet_link_tag "css/bootstrap-select/bootstrap-select.min", media: "all" %>
    <%= stylesheet_link_tag "css/jasny-bootstrap.min", media: "all" %>
    <%= stylesheet_link_tag "admin/sb-admin", media: "all" %>
    <meta name="robots" content="noindex">
	  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
		<link rel="icon" href="/favicon.ico" type="image/x-icon">

    <%= yield(:page_style) %>
<style>
/*#sidebar-menu li.active{background:#418bca;}*/

</style>
</head>
<body>
    <div id="wrapper">

        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/admin">InboxBiz CMS</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li style="border-right:1px solid #ccc;"><a href="/"><i class="fa fa-user fa-eye"></i> View Website</a></li>
                <li class="dropdown">
                	
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    	<%= current_user.username %>
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="<%= admin_logout_user_path %>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

        </nav>
        <!-- /.navbar-static-top -->
        
		<!-- start sidebar menu here -->
        	<%= render "layouts/menu_sidebar" %>
        <!-- end sidebar menu here -->

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><%= @title %></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- start page content here -->
            <div id="page_content" class="row">
            	<%= yield :page_content %>
            </div>
            <!-- end page content here -->
        </div>
        <!-- /#page-wrapper -->

    </div>
 




<%= javascript_include_tag "js/jquery-1.10.2.js" %>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "admin/sb-admin.js" %>
<%= javascript_include_tag 'ckeditor/ckeditor.js' %>
<%= javascript_include_tag "js/plugins/metisMenu/jquery.metisMenu.js" %>
<%= javascript_include_tag "js/plugins/morris/raphael-2.1.0.min.js" %>
<%= javascript_include_tag "js/plugins/morris/morris.js" %>
<%= javascript_include_tag "js/plugins/dataTables/jquery.dataTables.js" %>
<%= javascript_include_tag "js/plugins/dataTables/dataTables.bootstrap.js" %>
<%= javascript_include_tag "js/bootstrap-datepicker" %>
<%= javascript_include_tag "js/bootstrap-select/bootstrap-select" %>
<%= javascript_include_tag "js/jasny-bootstrap.min" %>

<%= yield(:page_scripts) %>
<script>
	CKEDITOR.config.allowedContent = true;

  $(function(){
	  $('.selectpicker').selectpicker();
	  $('.fileinput').fileinput();
      <% if flash.any? %>
          <% flash.each do |k,v| %>
            $('#page_content').displayAlert('<%= k %>', '<%= v %>')
          <% end %>
      <% end %>
      current_page = "<%= controller_name %>";
      if($('#li-' + current_page).length > 0){
          $('#li-' + current_page).addClass('active');
      }
	})
</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WaterDistrict</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
<%= yield %>

</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Mariveles Water District</title>
  <%= render 'shared/meta_info' %>
  <%= csrf_meta_tags %>
  <!-- CSS -->
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'css/bootstrap.css' %>
  <%= stylesheet_link_tag 'font-awesome/css/font-awesome.css' %>
  <%= stylesheet_link_tag 'css/front/styles', media: 'all' %>
  <!--page specific styles goes here -->
  <%= yield :page_styles %>
  <!--page specific styles ends here -->

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <script src="js/respond.min.js"></script>
  <![endif]-->
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<link rel="icon" href="/favicon.ico" type="image/x-icon">
</head>

<body>
<%= render 'shared/fb_init' %>



<%= yield :page_content %>


<!--contents ends here -->


<!-- Scripts -->

<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'main' %>
<%= yield :page_scripts %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55966112-1', 'auto');
  ga('send', 'pageview');

</script>
</body>



</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <title><%= @meta[:title] %></title>
    <%= render 'shared/meta_info' %>
    <%= csrf_meta_tags %>
    <!-- CSS -->
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'css/bootstrap.css' %>
    <%= stylesheet_link_tag 'font-awesome/css/font-awesome.css' %>
    <%= stylesheet_link_tag 'css/front/styles', media: 'all' %>

  <!--page specific styles goes here -->
    <%= yield :page_styles %>
    <!--page specific styles ends here -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
    <![endif]-->
	  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
		<link rel="icon" href="/favicon.ico" type="image/x-icon">
</head>

<body>
<%= render 'shared/fb_init' %>
<!-- start header here -->
<%= render 'layouts/header'  %>
<!-- end header here -->

<% if @banners.any? %>
<!--banners goes here -->
<div class="" style="background:#edf2fa;;box-shadow:0 0 6px #3f4a91;;">
	<div class="col-md-9" style="padding:0;margin-right:0;">
		<%= render 'layouts/main_banners' %>
	</div>
	<!-- transparency seal goes here -->
	<div class="col-md-3" style="min-height:250px;">
		    <div style="margin:30px auto 0;width:120px;">
            <a href="/about-us/transparency-seal" title="Transparency Seal">
			<%= image_tag('/assets/front/content_transparency-seal.png', style: 'width:120px;')%>
			</a>
		</div>
        <div style="margin:20px auto;width:220px;">
        <a href="/about-us/transparency-seal" title="Transparency Seal">
          <%= image_tag('/assets/front/philgeps_banner.jpg', style: 'height:70px;width:220px')%>
        </a>

        </div>
	</div>
  <div class="clearfix"></div>
</div>
<!--banners ends here -->
<% end %>
<div class="clearfix"></div>
<div id="main-section" class="" style="margin-top: 20px;">

  <%= yield :page_content %>

</div>

<!-- footer starts here -->
<%= render 'layouts/footer'  %>
<!-- footer ends here -->

<!-- Scripts -->
<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'main' %>

<script type="text/javascript">
    $(document).ready(function ($) {
        var articles = $('#highlights-holder').find('.article');
        // delegate calls to data-toggle="lightbox"
        $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
            event.preventDefault();
            return $(this).ekkoLightbox({
                always_show_close: true
            });
        });

        if(articles.length > 0){
            loopArticles(0);
        };

        function loopArticles(idx){
            if(idx > (articles.length - 1)){
                idx = 0;
            }
            articles.eq(idx)
                    .delay(500)
                    .fadeIn(500, function(){
                        $('#h-loader').fadeOut();
                    })
                    .delay(7000)
                    .fadeOut(700, function(){
                        $('#h-loader').fadeIn(500);
                        loopArticles(idx+1);
                    });

        }
    });
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55966112-1', 'auto');
  ga('send', 'pageview');

</script>
<%= yield :page_scripts %>
</body>



</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
	<title><%= @meta[:title] %></title>
  <%= render 'shared/meta_info' %>
  <%= csrf_meta_tags %>


  <!-- CSS -->
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'css/bootstrap.css' %>
  <%= stylesheet_link_tag 'font-awesome/css/font-awesome.css' %>
  <%= stylesheet_link_tag 'css/front/styles', media: 'all' %>
  <!--page specific styles goes here -->
  <%= yield :page_styles %>
  <!--page specific styles ends here -->

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <script src="js/respond.min.js"></script>
  <![endif]-->
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">

</head>

<body>
<%= render 'shared/fb_init' %>
<!-- start header here -->
<%= render 'layouts/header'  %>
<!-- end header here -->

<!--contents starts here -->
<% if @banners.any? %>
    <%= render 'layouts/main_banners'  %>
<hr class="page-divider">
<% else %>
<div style="margin-top: 20px;"></div>
<% end %>
<div id="page_content" class="container" style="margin-bottom:20px;">

<%= yield :page_content %>

</div>
<!--contents ends here -->

<!-- footer starts here -->
<%= render 'layouts/footer'  %>
<!-- footer ends here -->

<!-- Scripts -->

<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'main' %>
<script type="text/javascript">
    $(document).ready(function ($) {
        var articles = $('#highlights-holder').find('.article');
        // delegate calls to data-toggle="lightbox"
        $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
            event.preventDefault();
            return $(this).ekkoLightbox({
                always_show_close: true
            });
        });

        if(articles.length > 0){
            loopArticles(0);
        };

        function loopArticles(idx){
            if(idx > (articles.length - 1)){
                idx = 0;
            }
            articles.eq(idx)
                    .delay(500)
                    .fadeIn(500, function(){
                        $('#h-loader').fadeOut();
                    })
                    .delay(5000)
                    .fadeOut(1000, function(){
                        $('#h-loader').fadeIn();
                        loopArticles(idx+1);
                    });

        }
    });
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55966112-1', 'auto');
  ga('send', 'pageview');

</script>
<%= yield :page_scripts %>
</body>



</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html lang="en"><head>
    
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="">
    <meta name="author" content="">
    <%= csrf_meta_tags %>
	<title>InboxBiz CMS | Login</title>

    <!-- Core CSS - Include with every page -->
     <!-- Core CSS - Include with every page -->
  	<%= stylesheet_link_tag "css/bootstrap.min.css", media: "all" %>
  	<%= stylesheet_link_tag "font-awesome/css/font-awesome.css", media: "all" %>
  	
	<%= stylesheet_link_tag "admin/sb-admin.css", media: "all" %>
    
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-57-precomposed.png">
	<style>
		
		.col-centered{
		    float: none;
		    margin: 0 auto ;
		}
		.col-centered img {
			width:120px;
		}
	
	</style>
</head>

<body>

    <div class="container">
    	<%= yield %>
    </div>


<!-- Core Scripts - Include with every page -->
<%= javascript_include_tag "js/jquery-1.10.2.js" %>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "js/bootstrap.min.js" %>
<%= javascript_include_tag "js/plugins/metisMenu/jquery.metisMenu.js" %>


<!-- SB Admin Scripts - Include with every page -->
<%= javascript_include_tag "admin/sb-admin.js" %>
<script>



		
	/* type can be either of the ff
	 alert-success
	 alert-info
	 alert-warning
	 alert-danger
	*/
	$.fn.displayAlert = function(type, msg){
		if(type == ''){
			type = 'alert-warning'; 
		}
		
		aBox = '<div class="alert ' + type + ' alert-dismissable" style="margin-top:15px;">' +
	            '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>' +
	             msg +
	        '</div>';
	    this.prepend(aBox);
	    $('.alert').fadeOut(1000)
	};
	
	
	$.fn.greenify = function() {
	    this.css( "color", "green" );
	};
</script>
</body>

</html>